name: coca_lints
description: Strict linting rules for Dart to enhance code quality and readability.
version: 1.0.1
repository: https://github.com/cocahonka/coca-lints
topics:
  - analysis
  - analyzer
  - lint
  - lints
  - linter

environment:
  sdk: ^3.7.0
